# The file contains project related settings
# Key shall not contain any special characters
# Values with multiple lines shall be avoided
#
#Fri Dec 01 14:33:41 CST 2023
RTA-A2L/12.1.0/CLEAN_FWD_CONTENT_SETTING=false
RTA-A2L/12.1.0/DELETE_FWD_FILE=true
RTA-A2L/12.1.0/ENABLE_HOOK=DELETE_FWD_FILE
RTA-A2L/12.1.0/GENERATE_DEFAULTS=false
RTA-A2L/12.1.0/IS_SELECTED_FOR_UCG=false
RTA-A2L/12.1.0/KEY_A2L_INCLUDE_AR_FILES=
RTA-A2L/12.1.0/KEY_A2L_INCLUDE_AR_FILES_EXTERNAL=
RTA-A2L/12.1.0/KEY_A2L_INCLUDE_AR_FILES_LINKED=
RTA-A2L/12.1.0/KEY_A2L_INCLUDE_OPTIONS_FILE_PATH={OUTPUT_LOC}/src/a2l/optionsfile.opt
RTA-A2L/12.1.0/KEY_ADVANCED_COMMANDS=
RTA-A2L/12.1.0/KEY_ASAP_VERSION=V1_61
RTA-A2L/12.1.0/KEY_ENABLE_FUNCTION_UPDATER=n
RTA-A2L/12.1.0/KEY_FDEF_LIST=
RTA-A2L/12.1.0/KEY_INPUT_ARXML_FILES={OUTPUT_LOC}/src/a2l/arxmlFileList.txt
RTA-A2L/12.1.0/KEY_LANGUAGE=EN
RTA-A2L/12.1.0/KEY_MC_SUPPORTED_FILE_PATH=
RTA-A2L/12.1.0/KEY_OPTIONS_FILE_INPUT_TEXT_VALUE=
RTA-A2L/12.1.0/KEY_OPTIONS_FILE_LINK_TO_FILE=false
RTA-A2L/12.1.0/KEY_RESTORE_MCSUPPORT_FILES=false
RTA-A2L/12.1.0/KEY_STATIC_RECORD_LAYOUT=n
RTA-A2L/12.1.0/Options_File=
RTA-A2L/12.1.0/dir_log={OUTPUT_LOC}/_log
RTA-A2L/12.1.0/dir_out={OUTPUT_LOC}/src/a2l
RTA-BSW/12.1.0/ChkFlagsGen=15
RTA-BSW/12.1.0/DELETE_FWD_FILE_ON_FAILURE=true
RTA-BSW/12.1.0/GENERATE_DEFAULTS=false
RTA-BSW/12.1.0/GenARXML=true
RTA-BSW/12.1.0/GenIntegration=true
RTA-BSW/12.1.0/GenStatic=true
RTA-BSW/12.1.0/GenValidate=false
RTA-BSW/12.1.0/GenerateCH=true
RTA-BSW/12.1.0/Module_Bfx={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_BswM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_BswM_PB_Variant_Only={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_BswM_PreCompile_and_PB_Variant={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_CanIf={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_CanNm={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_CanNm_PB_Variant_Only={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_CanNm_PreCompile_and_PB_Variant={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_CanSM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_CanTSyn={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_CanTp={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_CanTp_PBL={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_CanTp_PBS={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_CanTp_PC={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_CanTrcv={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Com={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_ComM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_ComStack={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_ComXf={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Compiler={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Crc={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_CryIf={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Crypto={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Csm={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Dcm={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Dem={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Det={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Dlt={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_DoIP={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_DoIP_PB_Loadable={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_DoIP_PB_Selectable={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_DoIP_PreCompile={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_E2E={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_E2EXf={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Ea={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_EcuM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Efx={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_EthIf={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_EthSM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_EthTSyn={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_EthTrcv={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Fee={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_FiM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_FiM_PBL={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_FiM_PBS={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_FiM_PC={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_FrIf={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_FrNm={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_FrNm_PB_Variant_Only={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_FrNm_PreCompile_and_PB_Variant={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_FrSM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_FrTp={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_FrTp_PB_Loadable={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_FrTp_PB_Selectable={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_FrTp_PreCompile={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_FrTrcv={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_IdsM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Ifl={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Ifx={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_IpduM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_J1939Dcm={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_J1939Nm={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_J1939Rm={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_J1939Tp={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_J1939Tp_PB_Loadable={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_J1939Tp_PB_Selectable={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_J1939Tp_PreCompile={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_KeyM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_LdCom={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_LinIf={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_LinSM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_LinTrcv={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_MemIf={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Mfl={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Mfx={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Nm={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_NvM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_PduR={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Platform={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_ArxmlGen={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_BswSrv={isConfigured\=true, isSelected\=true}
RTA-BSW/12.1.0/Module_Rba_CCL={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_ComStackCdd={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_CryptoCCL={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_CryptoHSM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_DemObdBasic={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_DiagLib={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_EaFs2={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_EthArp={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_EthAutoIp={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_EthDHCP={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_EthICMP={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_EthIPv4={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_EthIPv6={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_EthIcmpV6={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_EthNdp={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_EthTcp={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_EthUdp={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_FeeFs1x={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_MemLib={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_XCoreCdd={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rba_Xfrm={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rte_Rips={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rte_Rips_CSXfrm={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Rte_Rips_SRCom={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Sd={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_SecOC={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_SoAd={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_SomeIpTp={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_SomeIpXf={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Standard={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_StbM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_TcpIp={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_UdpNm={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_WdgIf={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_WdgM={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/Module_Xcp={isConfigured\=false, isSelected\=false}
RTA-BSW/12.1.0/OutputPath={OUTPUT_LOC}/src/bsw/
RTA-BSW/12.1.0/SelectAll=false
RTA-BSW/12.1.0/com.bosch.bsw.abort_on_oaw_script_error=false
RTA-BSW/12.1.0/dir_log={OUTPUT_LOC}/_log
RTA-BSW/12.1.0/dir_out={OUTPUT_LOC}/src/bsw/
RTA-CAR/1.0.0/GENERATE_DEFAULTS=false
RTA-CAR/1.0.0/PROJECT_TYPE=GENERIC_PROJECT
RTA-CAR/1.0.0/RTA-A2L=12.1.0
RTA-CAR/1.0.0/RTA-BSW=12.1.0
RTA-CAR/1.0.0/RTA-MEMMAP=12.1.0
RTA-CAR/1.0.0/RTA-OS=12.1.0
RTA-CAR/1.0.0/RTA-RTE=12.1.1
RTA-CAR/1.0.0/dir_out={PROJECT_LOC}
RTA-MEMMAP/12.1.0/Additionalcommands=
RTA-MEMMAP/12.1.0/GENERATE_DEFAULTS=false
RTA-MEMMAP/12.1.0/IS_SELECTED_FOR_UCG=false
RTA-MEMMAP/12.1.0/Include_AR_Files={PROJECT_LOC}/system_config/rba_CUCELSwAddrMethod_BSWMD.arxml,{PROJECT_LOC}/system_config/rba_CUCELCompuMethods_BSWMD.arxml,{PROJECT_LOC}/system_config/rba_CUCELSwAddrMethodAddOn_BSWMD.arxml
RTA-MEMMAP/12.1.0/KEY_MEMMAPGEN_COMMAND_INPUT_TEXT_VALUE=
RTA-MEMMAP/12.1.0/KEY_MEMMAPGEN_COMMAND_LINKED_FILE_PATH=
RTA-MEMMAP/12.1.0/KEY_MEMMAPGEN_COMMAND_LINK_TO_FILE=false
RTA-MEMMAP/12.1.0/MemMap_Gen_Command=
RTA-MEMMAP/12.1.0/VALUE_UNSELECTED_PREVIOUS_CATEGORY=
RTA-MEMMAP/12.1.0/armemmap_tool_log={OUTPUT_LOC}/_log/armemmap_tool.txt
RTA-MEMMAP/12.1.0/armemmap_user_log={OUTPUT_LOC}/_log/armemmap_user.txt
RTA-MEMMAP/12.1.0/arxmlFilelist=D:/ProjectTestNXP/S32K344_DEMO/S32K344_ETAS/src/memmap/arxmlFileList.txt
RTA-MEMMAP/12.1.0/customer_templates=
RTA-MEMMAP/12.1.0/dir_log={OUTPUT_LOC}/_log/
RTA-MEMMAP/12.1.0/dir_out={OUTPUT_LOC}/src/memmap
RTA-MEMMAP/12.1.0/list_armemmap_h_files=D:/ProjectTestNXP/S32K344_DEMO/S32K344_ETAS/src/memmap/genfilelist.txt
RTA-MEMMAP/12.1.0/list_armemmap_h_files_prev=D:/ProjectTestNXP/S32K344_DEMO/S32K344_ETAS/src/memmap/prevGenfilelist.txt
RTA-MEMMAP/12.1.0/machine_family=MCU_RB_GENERIC
RTA-MEMMAP/12.1.0/memmapgen_output_path={OUTPUT_LOC}/src/memmap
RTA-MEMMAP/12.1.0/pathTomemmapFileDir={OUTPUT_LOC}/src/memmap
RTA-MEMMAP/12.1.0/platform_templates=D:/ProjectTestNXP/S32K344_DEMO/S32K344_ETAS/src/memmap/platformtemplates.txt
RTA-MEMMAP/12.1.0/strict_validate_missing_pragmas=n
RTA-MEMMAP/12.1.0/validate_start_stop_for_armemmap=n
RTA-OS/12.1.0/Additional=
RTA-OS/12.1.0/Additionalcommands=
RTA-OS/12.1.0/BuildType=
RTA-OS/12.1.0/CLEAN_FWD_CONTENT_SETTING=false
RTA-OS/12.1.0/DELETE_FWD_FILE=true
RTA-OS/12.1.0/ENABLE_HOOK=DELETE_FWD_FILE
RTA-OS/12.1.0/GENERATE_DEFAULTS=false
RTA-OS/12.1.0/Include_AR_files={PROJECT_LOC}/ecu_config/os/internal/Os_EcucValues.arxml
RTA-OS/12.1.0/Include_Folders=
RTA-OS/12.1.0/KEY_OS_COMMAND_INPUT_TEXT_VALUE=
RTA-OS/12.1.0/KEY_OS_COMMAND_LINK_TO_FILE=false
RTA-OS/12.1.0/Os_Compiler_Path=
RTA-OS/12.1.0/Os_command=
RTA-OS/12.1.0/ReferenceLibText=
RTA-OS/12.1.0/Reports=
RTA-OS/12.1.0/SampleHeaderFiles=
RTA-OS/12.1.0/SampleProjects=
RTA-OS/12.1.0/VALUE_UNSELECTED_PREVIOUS_CATEGORY=
RTA-OS/12.1.0/VRTA_3.0.49=VS2022
RTA-OS/12.1.0/Verbosity=
RTA-OS/12.1.0/dir_log={OUTPUT_LOC}/_log/
RTA-OS/12.1.0/dir_out={OUTPUT_LOC}/src/os
RTA-RTE/12.1.1/CLEAN_FWD_CONTENT_SETTING=false
RTA-RTE/12.1.1/DELETE_FWD_FILE=true
RTA-RTE/12.1.1/ENABLE_HOOK=DELETE_FWD_FILE
RTA-RTE/12.1.1/GENERATE_DEFAULTS=false
RTA-RTE/12.1.1/RTE_COMMAND_INPUT_TEXT_VALUE=
RTA-RTE/12.1.1/RTE_COMMAND_LINKED_FILE_PATH=
RTA-RTE/12.1.1/RTE_COMMAND_LINK_TO_FILE=false
RTA-RTE/12.1.1/RTE_Command=
RTA-RTE/12.1.1/dir_log={OUTPUT_LOC}/_log/
RTA-RTE/12.1.1/dir_out={OUTPUT_LOC}/src/rte
RTA-RTE/12.1.1/ecuinstance=/DBC_SysDesc_Can_Network_test0/Pkg_Ecu/New_Node_1
RTA-RTE/12.1.1/rtegen_files.lst={PROJECT_LOC}/DBC_SysDesc.arxml,{PROJECT_LOC}/EcucValueCollection_Generated.arxml,{PROJECT_LOC}/ISOLAR_PlatformTypes.arxml,{PROJECT_LOC}/_fwd/ecuc_configuration_values_fwd.arxml,{PROJECT_LOC}/ecu_config/os/internal/Os_EcucValues.arxml,{PROJECT_LOC}/ecu_config/rte/internal/Rte_EcucValues.arxml,{PROJECT_LOC}/system_config/AISpecification_PhysicalDimension_SWCD.arxml,{PROJECT_LOC}/system_config/AISpecification_Unit_SWCD.arxml,{PROJECT_LOC}/system_config/ComStack_Types.arxml,{PROJECT_LOC}/system_config/PlatformBaseOld_Types.arxml,{PROJECT_LOC}/system_config/PlatformBase_Types.arxml,{PROJECT_LOC}/system_config/PlatformOld_Types.arxml,{PROJECT_LOC}/system_config/PlatformSwBasePatch_Types.arxml,{PROJECT_LOC}/system_config/Platform_Types.arxml,{PROJECT_LOC}/system_config/Standard_Types.arxml,{PROJECT_LOC}/system_config/System.arxml,{PROJECT_LOC}/system_config/rba_BswSrv_EcucValues.arxml,{PROJECT_LOC}/system_config/rba_CUCELCompuMethods_BSWMD.arxml,{PROJECT_LOC}/system_config/rba_CUCELSwAddrMethodAddOn_BSWMD.arxml,{PROJECT_LOC}/system_config/rba_CUCELSwAddrMethod_BSWMD.arxml